{% set name = "jupyter-ai-magics" %}
{% set version = "2.31.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyter_ai_magics-{{ version }}.tar.gz
  sha256: 6bbe3266ebf02f774114b8012d10edd2b1f8dc65aa8647693b64dc80a3b8326e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.4.0
    - hatch-nodejs-version
    - pip
    - hatch-jupyter-builder
  run:
    - python >={{ python_min }}
    - ipython
    - importlib-metadata >=5.2.0
    - langchain >=0.3.0,<0.4.0
    - langchain-community >=0.3.0,<0.4.0
    - pydantic >=2.10.0,<3.0
    - click >=8.1,<9
    - jsonpath-ng >=1.5.3,<2

test:
  imports:
    - jupyter_ai_magics
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Jupyter AI magic commands
  home: https://github.com/jupyterlab/jupyter-ai
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dlqqq
    - 3coins
    - andrii-i
    - srdas
