{% set name = "jupyter-ai-magics" %}
{% set version = "2.28.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyter_ai_magics-{{ version }}.tar.gz
  sha256: 4e03f2001818d83a4ce8a025d0a07673769e03a5e5e5ab1f1478bba540432866

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.4.0
    - hatch-nodejs-version
    - pip
    - hatch-jupyter-builder
  run:
    - python >={{ python_min }}
    - ipython
    - importlib-metadata >=5.2.0
    - langchain >=0.2.17,<0.3.0
    - langchain-community >=0.2.19,<0.3.0
    - typing-extensions >=4.5.0
    - click >=8.0,<9.dev0
    - jsonpath-ng >=1.5.3,<2

test:
  imports:
    - jupyter_ai_magics
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Jupyter AI magic commands
  home: https://github.com/jupyterlab/jupyter-ai
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dlqqq
    - 3coins
    - andrii-i
    - srdas
